### ISSUE TITLE
high gas limit gets used causing transaction to fail

### ISSUE THREAD

**Issue by manishbista28** [web3labs/ice-substrate#241]
**Description**

Blockchain returns fairly large value of gas limit for some specific methods when estimateGas() is done.

We first faced the problem while calling a method called addLink(). This method is called only during contract deployment phase and we got past this by hard-coding the gas limit on truffle config. Easy workaround because we had to do it once.

But recently, another team reported that another method called transferNativeCoin() that is necessary for token transfer also exhibited the same problem. Since this method is called by any dapp that tries to build on top of BTP, it does not have an easy workaround as all dapps will now have to know that estimateGas() is broken.

As of this point, we do not know what other commonly used (crucial) methods are affected.

the high gas estimation was seen on arctic testnet only after it was upgraded  few weeks back

Example of estimate:
Contract | Method | GasEstimate | GasUsed
BMC | addLink | 243,955,001 | ~600,000
BTS | transferNativeCoin | 126,879,859 | ~700K

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. Call BTS Contract's transferNativeCoin method using deployed contract present [here](https://github.com/icon-project/icon-bridge/blob/main/docs/testnet_deployment.json#L63)
2. Manually set gas limit to the values above and retry

**Expected vs. Actual Behavior**

estimateGas() should return acceptable values for all contract methods

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system:
- Template version/tag:
- Rust version (run `rustup show`):

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._

**Additional Information**

_Please add any other details that you think may help us solve your problem._

**Comment by sharma66mahesh** [comment]
The issue seems to be reproduced when estimating gas for a transaction that calls multiple contracts and is already discussed [here](https://github.com/paritytech/frontier/issues/955). That seems to be detected only after the [last GAS related update](https://github.com/web3labs/ice-substrate/commit/77511cbf574148af6496acf29044db232eb0b34a) on the repo (_increasing BASE GAS, and keeping the same BLOCK GAS LIMIT_).

I deployed two contracts; an ERC20 token contract and an exchange contract. 
I estimated the gas and called the `approve` method on the token contract and `addLiquidity` method (_this makes a call to token contract_) on the exchange contract. These are my findings:

**On v0.4.58:**
Calling approve method 

- [ ] Estimated gas limit: 46894, 
- [ ] Gas used: 46894 (100%)
Calling addLiquidity method

- [ ] Estimated gas limit: 18704503, 
- [ ] Gas used: 45781 (0.2%)


**On v0.4.51:**
Calling approve method 

- [ ] Estimated gas limit: 46894, 
- [ ] Gas used: 46894 (100%)

Calling addLiquidity method

- [ ] Estimated gas limit: 1341221, 
- [ ] Gas used: 49665 (3.7%)


**On Polygon Mumbai Testnet:**
Calling approve method 

- [ ] Estimated gas limit: 46894, 
- [ ] Gas used: 46894 (100%)

Calling addLiquidity method

- [ ] Estimated gas limit: 67917, 
- [ ] Gas used: 62881 (92.585%)
